
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/thatdaleguy03/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.5.0-25-generic - x86_64
...
